### ISSUE TITLE
メモリの開放

### ISSUE THREAD

**Issue by m0et4** [robogi-ichinen/minirobo#1]
mdb_spi_src/spi_mdb.cにあるsend_pwm関数なんですが、mallocはfreeしなくて良いのですか？

**Comment by chagama-g** [comment]
pwm値とio値を一時的に保存するために使ってるのでfreeすると値が消えてしまいます.
あと初回実行時にだけ初期化されるように修正しないといけません。

**Comment by m0et4** [comment]
しかし、これだと毎回動的アドレスを確保しているので、メモリリークが起こる可能性があるのではないのですか。

**Comment by chagama-g** [comment]
毎回というのはプログラムの実行をしたときのことですか。

**Comment by m0et4** [comment]
いぇｓ

**Comment by m0et4** [comment]
そうなのです

**Comment by chagama-g** [comment]
グローバル変数としてポインタのポインタを宣言し
mdb_init関数内でメモリ確保処理をするようにしました。
